### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by azeltov**
coreutils is required for deployment

### CODE REVIEW

**Review by tybritten — APPROVED** [review]
LGTM

**Review by albscui — CHANGES_REQUESTED** [review]
I think we should just remove the dependency on `realpath` so we don't have to force our users to install `coreutils`.

**Comment by azeltov** [comment]
That would be even cleaner

**Comment by albscui** [comment]
Thank you @azeltov for catching this! I removed realpath dependency here https://github.com/pachyderm/aml/commit/d59b7d0f539c63289e66008dc16047c2ddb2836e

Gonna close this PR.

**Pull request closed without merging**
